### ISSUE TITLE
Nodes Down event gets triggered when nodes aren't down.

### ISSUE THREAD

**Issue by mourginakis** [aviate-labs/node-monitor#102]
One of our users reported that they got a `Nodes Down` message when one of their nodes went into `UNASSIGNED` status.

### Email Subject:
```
All Systems Healthy
```

### Email Body:
```
🛑 Node(s) Compromised:
Data Center: [REDACTED]
Node Label: N/A
Node Status: UNASSIGNED
Node ID: [REDACTED]
Live Node Status: [REDACTED]

Node Monitor by Aviate Labs
Report Generated:
2023-10-27T09:27:34 UTC
Help us serve you better! Provide your
feedback!
```

Node Monitor chooses an email subject based on the status of the last node in the deque.
https://github.com/aviate-labs/node-monitor/blob/daf8ee36b5b1309692d3d8583701023ca68b6c54/node_monitor/node_monitor_helpers/messages.py#L67-L74

However, Node Monitor triggers a `messages.nodes_down_message` based on this logic here:
https://github.com/aviate-labs/node-monitor/blob/daf8ee36b5b1309692d3d8583701023ca68b6c54/node_monitor/node_monitor_helpers/get_compromised_nodes.py#L53-L61

**Comment by louisevelayo** [comment]
To do:
- [ ] In get compromised_nodes.py, trigger if node_a.status == UP or node_a.status == UNASSIGNED, node_b.status == DOWN or node_b.status == DEGRADED, node_c.status == DOWN or node_c.status == DEGRADED.
- [ ] Rename nodes_down_message() to nodes_compromised_message() in messages.py
- [ ]
