### ISSUE TITLE
remove unused features

### ISSUE THREAD

**Issue by louisevelayo** [aviate-labs/node-monitor#17]
**Context**: The current version of the Node monitor in production is sending notifications to the node provider only when their node(s) go down and sending daily status reports for all their nodes. However, the code base still contains features related to subnet changes, addition, and removal of nodes, which are no longer used in production. Keeping unused code in the code base makes maintenance more complex and could potentially lead to confusion for developers in the future.

**Problem**: The code base contains unused features related to subnet changes, addition, and removal of nodes, which are not being used in the production version of the Node monitor. This unused code serves no purpose and adds unnecessary complexity to the project.

**Solution**: @mourginakis  will take the lead on cleaning up the code base by first ensuring there is a back up of the current version and removing the unused features.

**Comment by mourginakis** [comment]
resolved in #53
