### ISSUE TITLE
fetch and filter all node provider API data

### ISSUE THREAD

**Issue by louisevelayo** [aviate-labs/node-monitor#28]
**Context:** The current version of the Node Monitor is limited to pulling data from the API for a specific node provider. This approach makes it challenging for other node providers to use the Node Monitor without cloning the repository and setting up their separate instances. As a result, the current setup is not scalable. 

**Problem:** The current version of the Node Monitor restricts its usability to only one node provider, requiring separate instances for each provider. This lack of scalability hinders the adoption of the Node Monitor by multiple node providers.

**Solution:** To address this limitation, a solution is proposed that involves pulling all data from the API and then filtering that data based on the credentials provided from a database. This solution/database is outlined in issue #29.

**Comment by mourginakis** [comment]
Resolved in #53
