### ISSUE TITLE
add sqlite db for storing node provider details

### ISSUE THREAD

**Issue by louisevelayo** [aviate-labs/node-monitor#29]
**Context:** The current setup of the Node Monitor requires each node provider to individually set up their own instance, which can be a hindrance to adoption. To improve accessibility and encourage wider adoption, the proposed solution involves collecting credential data from node providers and implementing issues #26 and #28.

**Problem:** The requirement for each node provider to create their own instance of the Node Monitor can discourage adoption and create barriers to entry for potential users.

**Solution:** By collecting credential data from node providers and implementing issues #26 and #28, the Node Monitor can be run from one instance and made accessible to all node providers. The filtering of data based on individual credentials will ensure that each provider only has access to their relevant information.

**Comment by mourginakis** [comment]
I'd like to close this issue and open a new one for using Posgres with our NodeMonitorDB class. That way, whenever we want to change the settings, we can edit the settings on the network enabled database and node monitor will adapt during runtime.
