### ISSUE TITLE
add post endpoint to update node monitor configuration

### ISSUE THREAD

**Issue by louisevelayo** [aviate-labs/node-monitor#30]
Context: The current version of the Node monitor has a tedious and non-user-friendly configuration process, requiring direct access to the codebase or configuration files.

Problem: The configuration process for the Node monitor is error-prone and inconvenient for node providers who want to update their settings quickly and easily.

Solution: To improve the user experience and make it easier for node providers to configure and update the settings of the Node monitor, a web server (either Flask or FastAPI) will be implemented. This web server will expose POST endpoints.

**Comment by mourginakis** [comment]
Feeling it would be easier to just use a Postgres DB and update it manually from an application like DBeaver.
Unless DBeaver or equivalent software can make changes to an SQLite database over ssh or something.

**Comment by mourginakis** [comment]
Spent some time looking into this today. I suggest we open a managed postgres database on Digital Ocean and use that. That way we can edit the settings and have node monitor adapt during runtime. SQLite isn't meant to be accessed over a network and building POST endpoints for updating the config is likely more work than it's worth.
