### ISSUE TITLE
Unable to bind volumes to docker container

### ISSUE THREAD

**Issue by louisevelayo** [aviate-labs/node-monitor#52]
Issues with running Node Monitor on docker
- There seems to be an issue with binding volumes
- .env file isn't being loaded
- .json file isn't being loaded

### Steps to reproduce:
The problem arises when you type 
`docker compose up --build`
You also need a `tmp_prod_db.json`. This file is needed. See branch 'feature/minify'

**Comment by mourginakis** [comment]
Resolved in #53
