### ISSUE TITLE
Add Feature: Node Status Report

### ISSUE THREAD

**Issue by mourginakis** [aviate-labs/node-monitor#65]
We need Node Monitor to create and send a once-daily status report.
This status report must tell the recipient if any of their nodes are down, and if so, which ones.
It must be easily readable without the recipient having to do any math.
🩺 

Method:
- Create a new instance variable called `self.last_status_report`
- On every step, Node Monitor should check if `time.now() - self.last_status_report >= 1 day`
- If True, create and send out the status report.
- If False, do nothing

**Comment by louisevelayo** [comment]
The current notification message can be made more user friendly as it doesn't immediately tell the NP that their nodes are ok. NPs still need to remember the total number of nodes they have in production and make sure that is equal to the number of nodes "UP" + "UNASSIGNED"

**Solution:** The first line of the status report message should already indicate if action is required (this will tend to be what is seen on mobile notifications as well). More concretely:
- #nodes 'UP' + #nodes 'Unassigned' = #nodes in production --> No action required
- #nodes 'UP' + #nodes 'Unassigned' != #nodes in production --> Action required

After this first line, then the rest of details of the status report can be added (#nodes up, unassigned etc.) If you think of other data that could be included feel free to add that along.

Requirements:
- [ ]  Add fields (probably in the preference or channel detail table) to show the number of nodes a NP has in production
- [ ]  SQL query to get the number of nodes
- [ ]  Function to construct message (maybe in the directory node_monitor_helpers
