### ISSUE TITLE
Improve `Status` and `Node Down` Messages

### ISSUE THREAD

**Issue by mourginakis** [aviate-labs/node-monitor#82]
Below is the required output:
### Case: All Systems Healthy
**Subject:**
Node Status Report - All systems healthy

**Body:**
🔎Node Status Breakdown:
Total Nodes: 64
Nodes Up: 38/64
Nodes Down: none
Nodes Unassigned: 26/64
Nodes Disabled: none
Nodes Degraded: none

Thanks for reviewing today’s report. We’ll be back tomorrow! 
Node Monitor by [Aviate Labs](https://www.aviatelabs.co/).
Report generated: [Date & Time]
Help us serve you better! Provide your feedback [here](https://docs.google.com/forms/d/e/1FAIpQLSdBrvjpAbAZXB0EFu-ULp9AyUEm9i7EkZ84kBdin3xmyRVs6w/viewform?usp=sf_link).

### Case: Nodes Down
**Subject:**
Node Status Report - Action Required @ AN1

**Body:**
🛑Node(s) compromised:
Data center: AN1
Node Label: an1-dll20
Node Status: DOWN
Node ID: 7rkml-6hpmp-t2e4r-v6rab-iqugz-surqq-vcqxh-h7fld-rnts2-osixh-yqe 
Live Node Status: https://dashboard.internetcomputer.org/node/7rkml-6hpmp-t2e4r-v6rab-iqugz-surqq-vcqxh-h7fld-rnts2-osixh-yqe

🔎 Node Status Breakdown:
Total Nodes: 64
Nodes Up: 38/64
Nodes Down: 1/64
Nodes Unassigned: 26/64
Nodes Disabled: none
Nodes Degraded: none

#### Nodes down at one/multiple sites
**Subject:**
Node/s Down @ AN1, BR1

🛑 Node(s) compromised:

Data center: AN1
Node Label: an1-dll20
Node Status: DOWN
Node ID: 7rkml-6hpmp-t2e4r-v6rab-iqugz-surqq-vcqxh-h7fld-rnts2-osixh-yqe
Live Node Status: https://dashboard.internetcomputer.org/node/7rkml-6hpmp-t2e4r-v6rab-iqugz-surqq-vcqxh-h7fld-rnts2-osixh-yqe
Data center: BR1
Node Label: an1-dll20
Node Status: DOWN
Node ID: 7rkml-6hpmp-t2e4r-v6rab-iqugz-surqq-vcqxh-h7fld-rnts2-osixh-yqe
Live Node Status: https://dashboard.internetcomputer.org/node/7rkml-6hpmp-t2e4r-v6rab-iqugz-surqq-vcqxh-h7fld-rnts2-osixh-yqe

Node Monitor by [Aviate Labs](https://www.aviatelabs.co/).
Report generated: [Date & Time]
Help us serve you better! Provide your feedback [here](https://docs.google.com/forms/d/e/1FAIpQLSdBrvjpAbAZXB0EFu-ULp9AyUEm9i7EkZ84kBdin3xmyRVs6w/viewform?usp=sf_link).

**Comment by roald-av8** [comment]
Updated structure: _changed order "Total Nodes" & added Node Provider name_

Body:
🔎Node Status Breakdown:
Nodes Up: 38/64
Nodes Down: none
Nodes Unassigned: 26/64
Nodes Disabled: none
Nodes Degraded: none

Total Nodes: 64
Node Provider: _insert NP name_

Thanks for reviewing today’s report. We’ll be back tomorrow!
Node Monitor by [Aviate Labs](https://www.aviatelabs.co/).
Report generated: [Date & Time]
Help us serve you better! Provide your feedback [here](https://docs.google.com/forms/d/e/1FAIpQLSdBrvjpAbAZXB0EFu-ULp9AyUEm9i7EkZ84kBdin3xmyRVs6w/viewform?usp=sf_link).
